[package]
name = "av-metrics-decoders"
version = "0.1.0"
authors = ["Josh Holmer <jholmer.in@gmail.com>"]
edition = "2018"
description = "Decoders for use with av-metrics"
license = "MIT"
repository = "https://github.com/rust-av/av-metrics"
include = ["src/**/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
av-metrics = "0.6.1"
# FIXME: Once https://github.com/meh/rust-ffmpeg/pull/137 is merged and published, use the crates.io ffmpeg
#ffmpeg = { version = "0.3.0", optional = true, default-features = false, features = ["codec", "format", "ffmpeg_3_1"] }
ffmpeg = { git = "https://github.com/shssoichiro/rust-ffmpeg", branch = "versioning", optional = true, default-features = false, features = ["codec", "format", "ffmpeg_3_1"] }
y4m = { version = "0.7", optional = true }
